/**
 * src/lib/audio-injection.test.ts — regression guard for the build-audio.js
 * command-injection finding (CWE-78, card t_38e981ba, PoC by val-el).
 *
 * Defect it locks down: scripts/build-audio.js built the TTS command as a
 * SHELL STRING (`${venvPython} ${engine} --text "$(cat <file>)" --out <out>`)
 * and ran it through `execSync`, i.e. /bin/sh. `slug` is a FILENAME taken from
 * content/blog/*.mdx and was interpolated into that string; JSON.stringify()
 * only quotes a path, it does NOT stop command substitution inside double
 * quotes. So a file named `evil$(touch PWNEDMARKER)x.mdx` executed
 * `touch PWNEDMARKER` whenever the audio pipeline ran (`--recent N`, and the
 * nightly/publish cron which has .env.local with the service-role key loaded).
 * The same `file -b ${JSON.stringify(out)}` probe had the same shape, and an
 * unvalidated slug also allowed `../` to escape content/blog + .audio-out.
 *
 * These tests spawn the REAL CLI in a throwaway sandbox and assert the marker
 * file is NEVER created and the hostile slug is rejected. They FAIL against the
 * pre-fix `execSync` emitter (verified: marker created, exit 1 from the missing
 * TTS venv).
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

/* vitest rewrites import.meta.url to a non-file URL under jsdom, so resolve the
 * repo root from the process cwd (vitest sets it to the config/root dir). */
const REPO_ROOT = process.cwd();
const EMITTER = path.join(REPO_ROOT, "scripts", "build-audio.js");
if (!fs.existsSync(EMITTER)) {
  throw new Error(`build-audio.js not found from cwd ${REPO_ROOT} — run vitest from the repo root`);
}

const MARKER = "PWNEDMARKER";
/** The val-el PoC filename (minus ".mdx"), dropped into content/blog. */
const EVIL_SLUG = `evil$(touch ${MARKER})x`;
/** Injection hidden in the --voice argument instead of the filename. */
const EVIL_VOICE = `af_heart; touch ${MARKER}`;

const HEADER = [
  "/**",
  " * GENERATED by scripts/build-audio.js — do not hand-edit.",
  " */",
  'import type { ArticleAudio } from "@/lib/audio/contracts";',
  "",
  "export const articleAudio: ArticleAudio[] = [",
];

function mdx(title: string, date: string, body: string): string {
  return `---\ntitle: ${title}\ndate: ${date}\n---\n## ${title} section\n\n${body}\n`;
}

/**
 * Throwaway repo skeleton (script + narration dep + articles). `evil: true`
 * adds the malicious filename with the NEWEST date so `--recent 1` selects it;
 * `outside: true` adds a file one level ABOVE content/blog for the `../` case.
 */
function makeSandbox(opts: { evil?: boolean; outside?: boolean } = {}): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "audio-injection-"));
  fs.mkdirSync(path.join(dir, "scripts"), { recursive: true });
  fs.mkdirSync(path.join(dir, "src", "lib"), { recursive: true });
  fs.mkdirSync(path.join(dir, "src", "data"), { recursive: true });
  fs.mkdirSync(path.join(dir, "content", "blog"), { recursive: true });
  fs.copyFileSync(EMITTER, path.join(dir, "scripts", "build-audio.js"));
  fs.copyFileSync(
    path.join(REPO_ROOT, "src", "lib", "audio-narration.ts"),
    path.join(dir, "src", "lib", "audio-narration.ts"),
  );
  fs.writeFileSync(
    path.join(dir, "content", "blog", "benign-2026.mdx"),
    mdx("Benign", "2026-01-01", "This is a benign article body with prose to narrate."),
  );
  if (opts.evil) {
    fs.writeFileSync(
      path.join(dir, "content", "blog", `${EVIL_SLUG}.mdx`),
      mdx("Evil", "2026-12-31", "This article name tries to execute a shell command."),
    );
  }
  if (opts.outside) {
    // reachable from content/blog only via `../` — i.e. path traversal
    fs.writeFileSync(
      path.join(dir, "content", "outside-2026.mdx"),
      mdx("Outside", "2026-12-30", "This article lives outside content/blog."),
    );
  }
  fs.writeFileSync(
    path.join(dir, "src", "data", "audio.ts"),
    [...HEADER, "];", ""].join("\n"),
  );
  return dir;
}

/** Run the real emitter CLI inside `dir` (cwd = dir, so a `touch REL` lands there). */
function runEmitter(dir: string, args: string[]) {
  const res = spawnSync(process.execPath, ["scripts/build-audio.js", ...args], {
    cwd: dir,
    encoding: "utf-8",
    timeout: 60_000,
  });
  return {
    status: res.status,
    stdout: res.stdout ?? "",
    stderr: res.stderr ?? "",
    out: fs.readFileSync(path.join(dir, "src", "data", "audio.ts"), "utf-8"),
  };
}

function cleanup(dir: string) {
  fs.rmSync(dir, { recursive: true, force: true });
}

describe("build-audio.js rejects hostile slugs/voices (CWE-78 command injection)", () => {
  it("no shell is used at all: the emitter has no execSync and no $(cat …) string", () => {
    const src = fs.readFileSync(EMITTER, "utf-8");
    // no execSync CALL remains (comments may still name the old API) …
    expect(src).not.toMatch(/\bexecSync\s*\(/);
    // … the only subprocess spawn is the argv-array form …
    expect(src).toContain("execFileSync(");
    // … and the shell-string construction it replaced is gone
    expect(src).not.toContain("synthCmd");
  });

  it("a content/blog filename containing $(...) cannot execute a command", () => {
    const dir = makeSandbox({ evil: true });
    try {
      // NOT --metadata-only: the pre-fix bug fired on the synth path.
      const res = runEmitter(dir, ["--recent", "1", "--voice", "af_heart"]);
      expect(res.stderr).toMatch(/invalid slug/i);
      expect(res.status).not.toBe(0);
      // the injected command must not have run …
      expect(fs.existsSync(path.join(dir, MARKER))).toBe(false);
      // … and the hostile slug must not have produced intermediates/entries
      const audioOut = path.join(dir, ".audio-out");
      expect(fs.existsSync(audioOut) ? fs.readdirSync(audioOut) : []).toEqual([]);
      expect(res.out).not.toContain("evil");
    } finally {
      cleanup(dir);
    }
  });

  it("a hostile --voice argument cannot execute a command either", () => {
    const dir = makeSandbox();
    try {
      const res = runEmitter(dir, ["--recent", "1", "--voice", EVIL_VOICE]);
      expect(res.stderr).toMatch(/invalid voice/i);
      expect(res.status).not.toBe(0);
      expect(fs.existsSync(path.join(dir, MARKER))).toBe(false);
      expect(res.out).not.toContain("benign-2026");
    } finally {
      cleanup(dir);
    }
  });

  it("a ../ slug cannot read or emit a file outside content/blog (path traversal)", () => {
    const dir = makeSandbox({ outside: true });
    try {
      const res = runEmitter(dir, ["--metadata-only", "--slug", "../outside-2026", "--voice", "af_heart"]);
      expect(res.stderr).toMatch(/invalid slug/i);
      expect(res.status).not.toBe(0);
      expect(res.out).not.toContain("outside-2026");
    } finally {
      cleanup(dir);
    }
  });

  it("still emits normally for a legitimate slug + voice (guard does not break the pipeline)", () => {
    const dir = makeSandbox();
    try {
      const res = runEmitter(dir, ["--metadata-only", "--recent", "1", "--voice", "af_heart"]);
      expect(res.status).toBe(0);
      expect(res.out).toContain('slug: "benign-2026", voice: "af_heart"');
      expect(res.out).toContain('storagePath: "blog/benign-2026/af_heart.mp3"');
    } finally {
      cleanup(dir);
    }
  });

  it("accepts every slug shape the real blog uses (kebab-case) and the underscore voices", () => {
    const src = fs.readFileSync(EMITTER, "utf-8");
    /* mirror of SLUG_RE/VOICE_RE — a regression here silently rejects content */
    const SLUG_RE = /^[a-z0-9][a-z0-9-]*$/;
    const VOICE_RE = /^[a-z0-9][a-z0-9_-]*$/;
    expect(SLUG_RE.test("realtime-subscription-lifecycle-supabase-2026")).toBe(true);
    expect(VOICE_RE.test("af_heart")).toBe(true);
    expect(VOICE_RE.test("bm_george")).toBe(true);
    // the guard must actually reject the hostile shapes
    expect(SLUG_RE.test(EVIL_SLUG)).toBe(false);
    expect(SLUG_RE.test("../outside-2026")).toBe(false);
    expect(VOICE_RE.test(EVIL_VOICE)).toBe(false);
    expect(src).toContain("assertSafeSlug");
    expect(src).toContain("assertSafeVoice");
  });
});
