/**
 * src/lib/audio-emit.test.ts — regression guard for the build-audio.js emitter.
 *
 * Defect it locks down (t_c9caef59): scripts/build-audio.js used to seed its
 * entry list with `incremental ? readExistingEntries() : []`, so ANY run
 * without --incremental/--backfill (`--recent N`, `--slug X` — the usage the
 * script's own header documents) re-emitted src/data/audio.ts from scratch and
 * dropped every entry it did not re-synthesize, including its
 * timingsStoragePath. The audio-backfill cron committed that loss straight to
 * main (2 clobbers + a ~1.5h broken-main build outage on 2026-09-15).
 *
 * These tests spawn the REAL CLI in a throwaway sandbox (metadata-only, so no
 * TTS engine, no network, no Supabase) and assert the union survives — i.e.
 * they fail against the pre-fix `entries = incremental ? ... : []` emitter.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

/* vitest rewrites import.meta.url to a non-file URL under jsdom, so resolve the
 * repo root from the process cwd (vitest sets it to the config/root dir). */
const REPO_ROOT = process.cwd();
const EMITTER = path.join(REPO_ROOT, "scripts", "build-audio.js");
if (!fs.existsSync(EMITTER)) {
  throw new Error(`build-audio.js not found from cwd ${REPO_ROOT} — run vitest from the repo root`);
}

const HEADER = [
  "/**",
  " * GENERATED by scripts/build-audio.js — do not hand-edit.",
  " * Regenerate with: node scripts/build-audio.js --recent N --voice <v>",
  " * Contract types: src/lib/audio/contracts.ts.",
  " */",
  'import type { ArticleAudio } from "@/lib/audio/contracts";',
  "",
  "export const articleAudio: ArticleAudio[] = [",
];

/** Fixture on disk BEFORE the run: 3 entries, 2 of them with a timing manifest. */
const FIXTURE = [
  '  { slug: "alpha-2026", voice: "af_heart", storagePath: "blog/alpha-2026/af_heart.mp3", timingsStoragePath: "blog/alpha-2026/af_heart.timing.json" },',
  '  { slug: "legacy-pilot-2026", voice: "af_heart", storagePath: "blog/legacy-pilot-2026/af_heart.mp3", timingsStoragePath: "blog/legacy-pilot-2026/af_heart.timing.json" },',
  '  { slug: "legacy-pilot-2026", voice: "bm_george", storagePath: "blog/legacy-pilot-2026/bm_george.mp3" },',
].join("\n");

function mdx(title: string, date: string, body: string): string {
  return `---\ntitle: ${title}\ndate: ${date}\n---\n## ${title} section\n\n${body}\n`;
}

/** Write a throwaway repo skeleton (script + narration dep + 2 articles). */
function makeSandbox(audioTs = FIXTURE): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "audio-emit-"));
  fs.mkdirSync(path.join(dir, "scripts"), { recursive: true });
  fs.mkdirSync(path.join(dir, "src", "lib"), { recursive: true });
  fs.mkdirSync(path.join(dir, "src", "data"), { recursive: true });
  fs.mkdirSync(path.join(dir, "content", "blog"), { recursive: true });
  fs.copyFileSync(EMITTER, path.join(dir, "scripts", "build-audio.js"));
  fs.copyFileSync(
    path.join(REPO_ROOT, "src", "lib", "audio-narration.ts"),
    path.join(dir, "src", "lib", "audio-narration.ts"),
  );
  fs.writeFileSync(
    path.join(dir, "content", "blog", "alpha-2026.mdx"),
    mdx("Alpha", "2026-09-14", "This is the alpha article body with prose to narrate."),
  );
  fs.writeFileSync(
    path.join(dir, "content", "blog", "beta-2026.mdx"),
    mdx("Beta", "2026-09-01", "This is the beta article body with prose to narrate."),
  );
  fs.writeFileSync(
    path.join(dir, "src", "data", "audio.ts"),
    [...HEADER, audioTs, "];", ""].join("\n"),
  );
  return dir;
}

/** Run the real emitter CLI inside `dir`; returns its generated module. */
function runEmitter(dir: string, args: string[]) {
  const res = spawnSync(process.execPath, ["scripts/build-audio.js", ...args], {
    cwd: dir,
    encoding: "utf-8",
    timeout: 60_000,
  });
  return {
    status: res.status,
    stdout: res.stdout ?? "",
    stderr: res.stderr ?? "",
    out: fs.readFileSync(path.join(dir, "src", "data", "audio.ts"), "utf-8"),
  };
}

/** Independent parse of the generated module: one entry per `{ slug: … }` line. */
function entriesOf(mod: string) {
  return mod
    .split("\n")
    .filter((l) => l.startsWith("  { slug: "))
    .map((l) => {
      const g = (k: string) => new RegExp(`${k}: "([^"]+)"`).exec(l)?.[1];
      return {
        slug: g("slug")!,
        voice: g("voice")!,
        storagePath: g("storagePath")!,
        timingsStoragePath: g("timingsStoragePath"),
        line: l,
      };
    });
}

describe("build-audio.js emitter merges instead of replacing", () => {
  it("--recent N without --incremental keeps entries it did not regenerate, incl. timingsStoragePath", () => {
    const dir = makeSandbox();
    // alpha-2026 is the newest, so --recent 1 re-emits it; legacy-pilot-2026 is
    // NOT in the worklist and must survive untouched (with its timing manifest).
    const { status, out } = runEmitter(dir, ["--metadata-only", "--recent", "1", "--voice", "af_heart"]);
    expect(status).toBe(0);

    const entries = entriesOf(out);
    expect(entries.map((e) => `${e.slug}/${e.voice}`)).toEqual([
      "alpha-2026/af_heart",
      "legacy-pilot-2026/af_heart",
      "legacy-pilot-2026/bm_george",
    ]);
    expect(entries[1].timingsStoragePath).toBe("blog/legacy-pilot-2026/af_heart.timing.json");
    // and a metadata-only re-emit must not DOWNGRADE the regenerated entry
    expect(entries[0].timingsStoragePath).toBe("blog/alpha-2026/af_heart.timing.json");
  });

  it("--slug X without --incremental keeps every other entry", () => {
    const dir = makeSandbox();
    const { status, out } = runEmitter(dir, ["--metadata-only", "--slug", "beta-2026", "--voice", "af_heart"]);
    expect(status).toBe(0);

    const entries = entriesOf(out);
    expect(entries.map((e) => `${e.slug}/${e.voice}`)).toEqual([
      "alpha-2026/af_heart",
      "beta-2026/af_heart",
      "legacy-pilot-2026/af_heart",
      "legacy-pilot-2026/bm_george",
    ]);
    expect(entriesOf(out).filter((e) => e.timingsStoragePath)).toHaveLength(2);
  });

  it("the cron path (--backfill --slug <csv> --metadata-only) merges too", () => {
    const dir = makeSandbox();
    const { status, out } = runEmitter(dir, [
      "--backfill", "--metadata-only", "--slug", "beta-2026", "--voice", "af_heart",
    ]);
    expect(status).toBe(0);
    expect(entriesOf(out).map((e) => e.slug)).toEqual(["alpha-2026", "beta-2026", "legacy-pilot-2026", "legacy-pilot-2026"]);
    expect(entriesOf(out).filter((e) => e.timingsStoragePath)).toHaveLength(2);
  });

  it("re-emitting an already-merged file is byte-idempotent and keeps the exact format", () => {
    const dir = makeSandbox();
    const first = runEmitter(dir, ["--metadata-only", "--recent", "1", "--voice", "af_heart"]);
    expect(first.status).toBe(0);
    const second = runEmitter(dir, ["--metadata-only", "--recent", "1", "--voice", "af_heart"]);
    expect(second.status).toBe(0);
    expect(second.out).toBe(first.out);

    const lines = second.out.split("\n");
    expect(lines.slice(0, HEADER.length)).toEqual(HEADER);
    expect(second.out.endsWith("];\n")).toBe(true);
    expect(second.out.split("\n").at(-1)).toBe("");

    const slugs = entriesOf(second.out).map((e) => e.slug);
    expect(slugs).toEqual([...slugs].sort((a, b) => a.localeCompare(b)));
    // entries without a manifest stay exactly 3 fields wide — no stray key
    for (const e of entriesOf(second.out)) {
      if (!e.timingsStoragePath) expect(e.line).not.toContain("timingsStoragePath");
      expect(e.line.startsWith("  { slug: ")).toBe(true);
      expect(e.line.endsWith(" },")).toBe(true);
    }
  });

  it("an empty worklist still re-emits the full existing set (no truncation)", () => {
    const dir = makeSandbox();
    // --schema-less guard: a run whose target is already present must not erase the rest
    const { status, out } = runEmitter(dir, [
      "--backfill", "--metadata-only", "--slug", "alpha-2026", "--voice", "af_heart",
    ]);
    expect(status).toBe(0);
    expect(entriesOf(out)).toHaveLength(3);
    expect(out).toContain("timingsStoragePath");
  });
});
