/**
 * src/shared/contracts-constellations.ts — cross-sub-task contract types for
 * the Constellations + Chronicle achievement feature (backlog B-19 + B-18).
 *
 * Owned by brainiac (arch task t_3919afe1). Build sub-task workers IMPORT from
 * here. DO NOT EDIT this file directly — if a contract is wrong, the arch task
 * must be re-opened. Mirrors: docs/system-architecture-constellations.md.
 *
 * Domain: completion_events log (B-19 data foundation) + streak/rank derivation
 * + the P1/P2 visual surfaces (B-18). Additive-only — nothing here collides
 * with the existing completion types in contracts-course-catalog.ts; steel
 * WIDENS CompletionEventRow / DerivedProgress there per this spec (see
 * docs/010-constellation-foundation.sql + the decomposition-plan comment).
 */

/* ------------------------------------------------------------------ */
/*  B-19 — completion event types + envelope                          */
/* ------------------------------------------------------------------ */

/**
 * The full set of event types written to completion_events. Was
 * `'lesson' | 'course'`; B-19 widens the CHECK to add the three new kinds.
 *   - lesson       single lesson completed   (POST /api/progress/lesson)
 *   - course       entire course completed    (last lesson in a series)
 *   - quiz         a knowledge-check run      (POST /api/progress/quiz/run)
 *   - exam         a cert-prep EXAM passed >=72 (POST /api/progress/quiz/run)
 *   - certificate  user became certificate-eligible (/learn/[series]/certificate)
 *   - article      a signed-in user read a blog post (G1 — profile galaxy
 *                  free-floating stars; additive migration widens the CHECK)
 */
export type CompletionEventType =
  | "lesson"
  | "course"
  | "quiz"
  | "exam"
  | "certificate"
  | "article";

/**
 * Envelope stored in completion_events.metadata (jsonb). Carries the
 * server-derived score/tier for quiz/exam events; the eligible timestamp for
 * a certificate event. Never client-writable — always derived server-side.
 */
export interface CompletionMetadata {
  /** Server-derived score 0-100 (quiz / exam). */
  score?: number;
  /** Correct answers (quiz). */
  correct?: number;
  /** Total questions (quiz / exam). */
  total?: number;
  /** ISO timestamp of certificate eligibility (certificate event). */
  certifiedAt?: string;
  [key: string]: unknown;
}

/**
 * completion_events row — the widened shape (B-19). `event_type` now includes
 * the three new kinds and `metadata` is an optional jsonb envelope.
 */
export interface CompletionEventRow {
  id: number;
  user_id: string;
  course_id: string | null;
  event_type: CompletionEventType;
  lesson: number | null;
  lesson_slug: string | null;
  completed_at: string;
  /** Optional event envelope: score/tier for quiz/exam/certificate. */
  metadata?: CompletionMetadata | null;
}

/**
 * The idempotency key for appendCompletionEvent — what makes a duplicate write
 * a no-op. Mirrors the current guard (user + course + event_type + lesson_slug).
 */
export interface CompletionWriteKey {
  userId: string;
  courseId: string | null;
  eventType: CompletionEventType;
  lessonSlug?: string | null;
}

/** Parameters accepted by appendCompletionEvent (widened in B-19). */
export interface AppendCompletionInput {
  userId: string;
  courseId: string | null;
  eventType: CompletionEventType;
  lesson?: number | null;
  lessonSlug?: string | null;
  /** Optional envelope persisted to metadata (quiz/exam/certificate). */
  metadata?: CompletionMetadata;
}

/* ------------------------------------------------------------------ */
/*  B-19 — rank ladder                                                 */
/* ------------------------------------------------------------------ */

/**
 * Constellation-themed rank bands. ASCENDING — `ladder[0]` is the entry band.
 * A learner's current rank is the highest band whose thresholds are met.
 * Pure, deterministic, unit-testable (no DB state — bands live in code).
 */
export type RankId =
  | "starseed"
  | "wayfarer"
  | "explorer"
  | "polestar"
  | "celestial";

export interface RankBand {
  id: RankId;
  /** Display name. */
  name: string;
  /** Lessons required to reach this band. */
  lessonsRequired: number;
  /** Courses required to reach this band. */
  coursesRequired: number;
  /** One-line blurb for the profile rank-ladder row. */
  description: string;
}

/** A learner's current rank (highest reached band). */
export interface Rank {
  id: RankId;
  name: string;
  /** One-line blurb for tooltip/header. */
  description: string;
  /** Index of this band in `ladder`. */
  index: number;
  /** 0-100 progress toward the NEXT band (100 when at the top band). */
  nextProgressPct: number;
}

/** The profile rank-ladder payload (P2 full sky). */
export interface LadderProgress {
  /** All bands, ascending (position = index). */
  ladder: RankBand[];
  /** Derive-rank helper inputs. */
  lessonsCompleted: number;
  coursesCompleted: number;
  /** The learner's current band. */
  current: Rank;
}

/* ------------------------------------------------------------------ */
/*  B-18 — constellation + sky domain types                            */
/* ------------------------------------------------------------------ */

/** One star (lesson) in a course constellation. */
export interface ConstellationStar {
  /** Canonical lesson slug. */
  lessonSlug: string;
  /** 1-based lesson number. */
  index: number;
  /** Lesson display title/name (content-derived). */
  label: string;
  /** True when this lesson is completed (star lit). */
  lit: boolean;
}

/** Per-course constellation state — drives outline, hub preview, full sky. */
export interface ConstellationState {
  courseId: string;
  seriesSlug: string;
  name: string;
  /** Tailwind gradient classes (series.json). */
  gradient: string;
  /** Total planned stars (all lessons, incl. unpublished). */
  totalStars: number;
  /**
   * The curriculum's final lesson count (`series.json` → `curriculumLessons`).
   *
   * `totalStars` counts the lessons that exist today and grows as they land.
   * This is the number the finished course will have, so it is stable: the star
   * chart sizes a course's constellation from it, and a figure chosen for a
   * 40-lesson curriculum does not change shape when lesson 13 ships.
   *
   * Equals `totalStars` when the course has not declared a final size.
   */
  curriculumLessons: number;
  /** Lit (completed) stars. */
  litStars: number;
  /** True when every star is lit (course complete). */
  complete: boolean;
  /**
   * True when the cert-prep exam has been passed (best server-graded
   * `quiz_attempt` score for `<series>:exam` >= 72). This is the SINGLE
   * source of truth for the exam crown across every surface — profile sky,
   * on-course tracker, and certificate all read the same derived value, so
   * they can never disagree. (ADR: quiz_attempt is server-graded; quiz_run is
   * client-writable history and must never gate a crown or certificate.)
   *
   * Optional so content/synthetic surfaces (PathCard previews, guest locks,
   * tests) can omit it and get no crown; the server loaders set it.
   */
  examPassed?: boolean;
  stars: ConstellationStar[];
}

/** Streak + rank stat block shared by the P1 surfaces (nice + light). */
export interface AchievementStats {
  /** Live streak as-of `now` (B-19 fix: 0 if last completion not today/yesterday). */
  streakDays: number;
  longestStreakDays: number;
  rank: Rank | null;
  coursesCompleted: number;
  tracksCompleted: number;
}

/** One line of the Chronicle narrative feed (profile, P2). */
export interface ChronicleEntry {
  id: number;
  eventType: CompletionEventType;
  courseId: string | null;
  seriesSlug: string | null;
  /** Course display name (may be null for orphaned rows). */
  courseName: string | null;
  /** Human label: lesson name, "Quiz X/10", "Cert prep exam passed", "Certificate earned". */
  label: string;
  /** ISO completed_at. */
  completedAt: string;
  /** Server-derived score for quiz/exam entries; null otherwise. */
  score?: number | null;
}

/** /profile full-sky payload (server loader → client). */
export interface ProfileSky {
  stats: AchievementStats;
  constellations: ConstellationState[];
  chronicle: ChronicleEntry[];
  isGuest: boolean;
}

/* ------------------------------------------------------------------ */
/*  B-18 — P1/P2 surface component props                               */
/* ------------------------------------------------------------------ */

/** P1 — the "star ignition" moment on lesson completion. */
export interface ConstellationCelebrationProps {
  seriesSlug: string;
  courseName: string;
  lessonSlug: string;
  lessonLabel: string;
  /** Stars lit in the course AFTER this lesson. */
  litStars: number;
  totalStars: number;
  /** Live current streak as-of now (B-19 derivation). */
  streakDays: number;
  /** True when this lesson completes the course → pulse + longer moment. */
  courseJustCompleted: boolean;
  prefersReducedMotion?: boolean;
}

/** P1 — series-outline full constellation. */
export interface SeriesConstellationProps {
  constellation: ConstellationState;
  isGuest: boolean;
}

/** P1 — hub-card constellation preview (keep light — compact). */
export interface ConstellationPreviewProps {
  constellation: ConstellationState;
  /** Hub stays light: compact preview vs full detail. */
  compact?: boolean;
}

/** P1 — streak chip shown at the lesson-complete beat. */
export interface StreakCounterProps {
  streakDays: number;
  /** Inline vs stat-card treatment. */
  variant?: "inline" | "stat";
}

/** P2 — profile full sky section (aggregate constellations + ladder + feed). */
export interface FullSkySectionProps {
  sky: ProfileSky;
}

/** P2 — guest "locked sky" teaser (pairs with B-09). */
export interface LockedSkyTeaserProps {
  /** e.g. "/login?next=/profile". */
  ctaHref?: string;
}

/** P2 — certificate celebration: constellation completes + reveal. */
export interface CertificateCelebrationProps {
  seriesSlug: string;
  courseName: string;
  constellation: ConstellationState;
  streakDays: number;
}

/* ------------------------------------------------------------------ */
/*  API route shapes                                                   */
/* ------------------------------------------------------------------ */

/** GET /api/progress/achievement → AchievementStats (P1 pop + hub). */
export type AchievementResponse = { stats: AchievementStats };

/** POST /api/progress/lesson augmentation (no shape change — body unchanged). */
export interface LessonCompletionResponseBody {
  status: "ok" | "error" | "unauthenticated";
  /** Present only when the lesson completes its course. */
  courseJustCompleted?: boolean;
}