/**
 * src/shared/contracts-course-catalog.ts — cross-sub-task contract types for the
 * course-catalog + entitlements + admin build.
 *
 * Owned by brainiac (arch task t_22b26cb9). Sub-task workers (steel A–E)
 * IMPORT from here. DO NOT EDIT this file directly — if a contract is wrong,
 * reopen the arch task.
 *
 * Mirrors: docs/system-architecture-course-catalog-admin.html (t_22b26cb9)
 * DB source of truth: supabase/migrations/008_course_catalog.sql
 *
 * B-19 (t_e9c1c761) — steel WIDENS CompletionEventRow / DerivedProgress per
 * brainiac's arch (src/shared/contracts-constellations.ts + migration 010).
 * Additive-only: existing lesson/course rows and consumers are unchanged.
 */
import type {
  CompletionEventType,
  CompletionMetadata,
  Rank,
} from "@/shared/contracts-constellations";

/* ------------------------------------------------------------------ */
/*  Core enums (mirror DB CHECK constraints in migration 008)          */
/* ------------------------------------------------------------------ */

/** Course lifecycle state — lives in `courses.status`, NOT content files. */
export type CourseStatus = "pending" | "live" | "archived";

/** How a course is gated. Lives in `courses.access_model`. */
export type AccessModel =
  | "free"
  | "subscription"
  | "one-time"
  | "sub-or-one-time"
  | "granted";

/** How an entitlement was granted — source of truth in `user_entitlements.source`. */
export type EntitlementSource = "granted" | "one-time";

/** Role stored in `user_roles.role` (default member). */
export type UserRole = "admin" | "member";

/* ------------------------------------------------------------------ */
/*  DB row shapes (snake_case — mirror migration 008 columns)          */
/* ------------------------------------------------------------------ */

/** `courses` row — keyed by series_slug. Platform fields only; content stays in files. */
export interface CourseRow {
  id: string;
  series_slug: string;
  title: string;
  status: CourseStatus;
  access_model: AccessModel;
  /** Price in cents; NULL for free/granted/read-only. Display + future Stripe. */
  price_cents: number | null;
  launched_at: string | null;
  created_at: string;
  updated_at: string;
  /* ---- Learn Platform v2 (migration 009) — org + profile as data ----
     Optional because pre-009 rows/columns may be absent and existing test
     fixtures build CourseRow literals without them. Use `?? null` when
     reading. The unified CatalogCourse type carries the guaranteed shape. */
  /** FK → catalog_sections.id; NULL = uncategorized (hidden from public org view). */
  section_id?: string | null;
  /** FK → catalog_groups.id; NULL = standalone under the section. */
  group_id?: string | null;
  /** Track slug this course belongs to (e.g. "hermes-consultant"); NULL = standalone. */
  track?: string | null;
  /** Level within a track (1|2|3); NULL = standalone / Learning Path. */
  level?: number | null;
  /** Order within group/track; default 0. */
  sort_order?: number | null;
  /** Catalog-wide difficulty scale (plan §3c); NULL = not authored. */
  difficulty?: Difficulty | null;
  /** Human-readable "what level of knowledge helps" prose (plan §3c). */
  recommended_background?: string | null;
  /** Who it's for: Consultants, Developers, PMs, Cert candidates, Business Users. */
  audience?: string | null;
  /** 2-4 "what you'll be able to do after" strings (jsonb array). */
  learning_outcomes?: string[] | null;
  /** Course-level tags, distinct from per-lesson tags (text[]). */
  course_tags?: string[] | null;
}

/** `user_roles` row. */
export interface UserRoleRow {
  user_id: string;
  role: UserRole;
  updated_at: string;
}

/** `user_entitlements` row. revoked_at NULL = active. */
export interface UserEntitlementRow {
  id: string;
  user_id: string;
  course_id: string;
  source: EntitlementSource;
  grant_note: string | null;
  granted_by: string | null;
  granted_at: string;
  revoked_at: string | null;
}

/** `subscriptions` row — read-only display this build; nothing writes it except schema. */
export interface SubscriptionRow {
  id: string;
  user_id: string;
  plan: string;
  status: "active" | "trialing" | "canceled" | "past_due";
  current_period_end: string | null;
  created_at: string;
}

/** `admin_audit_log` row — read-only in the panel; every admin action writes one. */
export interface AdminAuditLogRow {
  id: number;
  actor_user_id: string | null;
  action: string;
  target_type: string;
  target_id: string | null;
  details: Record<string, unknown> | null;
  created_at: string;
}

/* ------------------------------------------------------------------ */
/*  src/lib/access.ts — the server-side access seam                    */
/* ------------------------------------------------------------------ */

/** Signed-in user's id; null for guests. */
export type UserId = string | null;

/** What a single course means to the current user on a catalog surface. */
export interface CatalogCourseEntry {
  course: CourseRow;
  /** Status-driven visibility: live (all), pending/archived (admin only). */
  visible: boolean;
  /** Model + entitlement-driven: may the user read gated content? */
  canAccess: boolean;
}

/** Full catalog the current user may see + their access per course. */
export interface CatalogForUserResult {
  entries: CatalogCourseEntry[];
  /** True when the caller is an admin (sees pending/archived). */
  isAdmin: boolean;
}

/** Access decision for a single course on a content surface (lesson/check/exam/cert/API). */
export type CourseAccessDecision =
  /** Course not live / no courses row → treat as not launched. */
  | { kind: "not-launched" }
  /** Admin previewing a pending/archived course → content renders. */
  | { kind: "admin-preview" }
  /** User may read gated content. */
  | { kind: "granted" }
  /** User must see the paywall (live + not entitled). */
  | { kind: "paywall" };

/** Access seam API surface — the single decision function every surface calls. */
export interface AccessSeam {
  /** Catalog for a surface: visible courses + per-course access. */
  getCatalogForUser: (userId: UserId) => Promise<CatalogForUserResult>;
  /** Single-course decision for a content surface. */
  decideCourseAccess: (
    userId: UserId,
    seriesSlug: string,
  ) => Promise<CourseAccessDecision>;
  /** Role check for /admin gating. */
  isAdmin: (userId: UserId) => Promise<boolean>;
}

/* ------------------------------------------------------------------ */
/*  Catalog + gating sweep — page/route contracts                      */
/* ------------------------------------------------------------------ */

/** Course row joined with content-derived display fields for catalog cards. */
export interface CatalogCourseView {
  course: CourseRow;
  /** Display name from series.json; fallback: humanized series_slug. */
  name: string;
  /** Description from series.json; fallback: "". */
  description: string;
  gradient: string;
  /** Published lesson count (from build data). */
  lessonCount: number;
  totalLessons: number;
  /** Final planned lesson count; equals `totalLessons` when undeclared. */
  curriculumLessons: number;
  /** User's access on this card (drives lock vs click-through). */
  canAccess: boolean;
}

/** Input contract for the gating sweep — same shape across lesson/check/exam/cert pages. */
export interface GatedContentPageProps {
  seriesSlug: string;
  lessonSlug?: string;
}

/** Canonical lesson slugs for a series (published only — pending excluded). */
export interface SeriesLessonSlugs {
  seriesSlug: string;
  lessonSlugs: string[];
}

/* ------------------------------------------------------------------ */
/*  Admin API contracts                                               */
/* ------------------------------------------------------------------ */

/** Admin course mutation body (US-009). */
export interface AdminCourseUpdateRequest {
  status?: CourseStatus;
  access_model?: AccessModel;
  price_cents?: number | null;
}

/** Admin course list row (US-009/014) — course + entitlement summary. */
export interface AdminCourseListRow {
  course: CourseRow;
  /** Number of active (non-revoked) granted/one-time entitlements. */
  activeEntitlementCount: number;
}

/** Admin user list row (US-010) — role + entitlements + subscription for the matrix. */
export interface AdminUserListRow {
  user_id: string;
  email: string;
  display_name: string | null;
  role: UserRole;
  /** Active entitlements keyed by course_id → source. */
  entitlements: Record<string, EntitlementSource>;
  /**
   * The user's subscription row that currently grants access (active/trialing,
   * not past its period end), or null when none. Read-only display — billing
   * writes are out of scope (ADR-204, billing on hold).
   */
  subscription: SubscriptionRow | null;
}

/** Grant/revoke request (US-012). */
export interface GrantEntitlementRequest {
  userId: string;
  courseId: string;
  note?: string;
}

/** Bulk grant request (US-013). */
export interface BulkGrantRequest {
  userIds: string[];
  courseId: string;
  note?: string;
}

/** Role assignment request (US-011). */
export interface SetRoleRequest {
  userId: string;
  role: UserRole;
}

/** Admin API success envelope. */
export interface AdminApiResponse<T> {
  ok: true;
  data: T;
}

/** Admin API error envelope (403 non-admin, 404, 400 validation). */
export interface AdminApiError {
  ok: false;
  error: string;
}

/* ------------------------------------------------------------------ */
/*  Paywall (Decide/Learn) — locked content surface                    */
/* ------------------------------------------------------------------ */

/** Access options surfaced on the paywall for a locked course. */
export interface PaywallAccessOption {
  model: AccessModel;
  /** e.g. "$299 one-time", "Subscribe for access", "Granted by admin". */
  label: string;
  /** True when this option is actionable (vs informational "granted"). */
  actionable: boolean;
}

/** Paywall props — server-rendered with the course's real access options. */
export interface PaywallView {
  courseName: string;
  gradient: string;
  /** First lesson slug readable as the peek (may be null). */
  peekLessonSlug: string | null;
  options: PaywallAccessOption[];
}

/* ------------------------------------------------------------------ */
/*  Learn Platform v2 — unified catalog contract (migration 009)       */
/*  Owned by brainiac (arch task t_e6b81ca5). Steel imports from here. */
/*  Mirrors: docs/system-architecture-learn-v2.html + docs/009-learn-  */
/*  catalog.sql. DO NOT EDIT directly — reopen the arch task.          */
/* ------------------------------------------------------------------ */

/** Catalog-wide difficulty scale (plan §3c) — on EVERY course. */
export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

/** `catalog_sections` row — top-level Learn sections. */
export interface CatalogSection {
  id: string;
  slug: string;
  name: string;
  sort_order: number;
  created_at: string;
}

/** `catalog_groups` row — a vendor/family group under a section. */
export interface CatalogGroup {
  id: string;
  section_id: string;
  slug: string;
  name: string;
  sort_order: number;
  created_at: string;
}

/** `course_prerequisites` row — structured "this course requires course X". */
export interface CoursePrerequisiteRow {
  id: string;
  course_id: string;
  required_course_id: string;
  sort_order: number;
  created_at: string;
}

/** A course this course requires — joined name + slug for the outline. */
export interface PrerequisiteCourse {
  /** series_slug of the required course (for the link). */
  series_slug: string;
  /** Display name of the required course. */
  name: string;
}

/** `completion_events` row — append-only completion foundation (ADR-211). */
export interface CompletionEventRow {
  id: number;
  user_id: string;
  course_id: string | null;
  event_type: CompletionEventType;
  lesson: number | null;
  lesson_slug: string | null;
  completed_at: string;
  /** Optional event envelope: score/tier for quiz/exam/certificate (B-19). */
  metadata?: CompletionMetadata | null;
}

/**
 * UNIFIED CATALOG COURSE (ADR-210) — the ONE shape every surface consumes:
 * hub, cards, paywall, admin, sitemap, APIs. Merges DB-derived org/profile/
 * access fields with content-derived display fields (series.json + lesson
 * files). No drift — a course is always built through buildCatalogCourse().
 */
export interface CatalogCourse {
  /* ---- DB-derived (courses + catalog_sections/groups + prerequisites) ---- */
  course: CourseRow;
  /** Joined section (may be null for uncategorized). */
  section: CatalogSection | null;
  /** Joined group (may be null for a standalone course). */
  group: CatalogGroup | null;
  /** Structured prerequisites (plan §3c) — auto-renders the outline section. */
  prerequisites: PrerequisiteCourse[];
  /** Next course id derived from track/level/sort_order (ADR-212); null = last. */
  nextCourseId: string | null;
  /* ---- content-derived (series.json + lesson files) ---- */
  /** Display name (series.json); fallback: humanized series_slug. */
  name: string;
  /** One-line description (series.json); fallback: "". */
  description: string;
  /** Tailwind gradient classes (series.json). */
  gradient: string;
  /** Published lesson count. */
  lessonCount: number;
  /** Total (incl. unpublished) lesson count. */
  totalLessons: number;
  /**
   * The curriculum's final planned lesson count (`series.json`).
   * Equals `totalLessons` when the course has not declared a finish line.
   */
  curriculumLessons: number;
  /* ---- access (from the access seam) ---- */
  visible: boolean;
  canAccess: boolean;
}

/** Sections + groups a catalog surface needs for bucketing. */
export interface CatalogOrganization {
  sections: CatalogSection[];
  groups: CatalogGroup[];
}

/** The next-course seam (ADR-212) — what to take next on a course surface. */
export interface CatalogNextCourse {
  /** course_id of the next course; null when this is the last in the track. */
  nextCourseId: string | null;
  /** True when the current user has completed every prerequisite (V2 "ready"). */
  prerequisitesMet: boolean;
}

/** Progress/rank derivation input — completion events for one user. */
export interface CompletionInput {
  /** The user's completion_events (RLS-scoped to owner). */
  events: CompletionEventRow[];
  /** Track membership per course_id (course_id → track slug). */
  courseTracks: Record<string, string>;
  now: string;
}

/** Derived progress/rank helpers (plan §3f) — pure, unit-testable, no DB cols. */
export interface DerivedProgress {
  /** Distinct lessons completed. */
  lessonsCompleted: number;
  /** Distinct courses completed (all their lessons done). */
  coursesCompleted: number;
  /** Distinct tracks completed (every course in the track done). */
  tracksCompleted: number;
  /** Current streak in whole days (≥1 consecutive day with a completion). */
  streakDays: number;
  /** Longest streak in whole days. */
  longestStreakDays: number;
  /** Min→max span across a course's events, in days (null if <2 events). */
  timeToCompleteDays: number | null;
  /** Current rank (highest reached band). Starseed (index 0) is the floor —
      even an empty learner is at least starseed, so this is never null. */
  rank: Rank;
}

/** Catalog surface → the user may see + their access per unified course. */
export interface CatalogForUserV2Result {
  courses: CatalogCourse[];
  isAdmin: boolean;
}

/* ------------------------------------------------------------------ */
/*  Admin — Learn v2 course profile + org form fields                  */
/* ------------------------------------------------------------------ */

/** Admin course mutation body (US-009 + Learn v2 profile/org fields). */
export interface AdminCourseUpdateRequest {
  status?: CourseStatus;
  access_model?: AccessModel;
  price_cents?: number | null;
  /* ---- Learn v2 (migration 009) ---- */
  section_id?: string | null;
  group_id?: string | null;
  track?: string | null;
  level?: number | null;
  sort_order?: number | null;
  difficulty?: Difficulty | null;
  recommended_background?: string | null;
  audience?: string | null;
  learning_outcomes?: string[] | null;
  course_tags?: string[] | null;
}

/** Admin profile upsert for catalog sections (US-009, Learn v2). */
export interface AdminSectionUpsertRequest {
  slug: string;
  name: string;
  sort_order?: number;
}

/** Admin profile upsert for catalog groups (US-009, Learn v2). */
export interface AdminGroupUpsertRequest {
  section_id: string;
  slug: string;
  name: string;
  sort_order?: number;
}

/** Admin prerequisite mutation (US-009, Learn v2). */
export interface AdminPrerequisiteRequest {
  courseId: string;
  requiredCourseIds: string[];
}

