/**
 * src/shared/contracts.ts — cross-sub-task contract types for the quiz-tier build.
 *
 * Owned by brainiac (arch task t_cf2e9661). Sub-task workers (content-gen,
 * implement, certificate) IMPORT from here. DO NOT EDIT this file directly —
 * if a contract is wrong, the arch task must be re-opened.
 *
 * Mirrors: docs/implementation-plan-quiz-tiers.md (t_cf2e9661)
 *
 * Merger addition (t_bf0336b5): re-exports the Adroit site+blog merger
 * cross-task contract types so steel workers import from the single canonical
 * contracts.ts path. See ./contracts-merger.ts.
 */
export * from "./contracts-merger";

/* ------------------------------------------------------------------ */
/*  Tier quiz identity                                                 */
/* ------------------------------------------------------------------ */

/** The three quiz tiers in the course progression model. */
export type QuizTier = "lesson" | "check" | "exam";

/**
 * Parsed form of a tier quiz name like `omni-studio-cert:lesson:day-01-f1`,
 * `omni-studio-cert:check:3`, or `omni-studio-cert:exam`.
 * `id` is the lesson slug, the check number as a string, or `"exam"`.
 */
export interface ParsedQuizName {
  series: string;
  tier: QuizTier;
  id: string;
}

/* ------------------------------------------------------------------ */
/*  Quiz data shape (identical across all three JSON tiers)            */
/* ------------------------------------------------------------------ */

export interface QuizQuestion {
  question: string;
  options: string[];
  correct_answer_index: number;
  explanation?: string;
}

export interface QuizData {
  quizName: string;
  title: string;
  description?: string;
  questions: QuizQuestion[];
}

/** Knowledge check descriptor — check n covers lessons [a, b]. */
export interface KnowledgeCheckMeta {
  n: number;
  lessons: [number, number];
}

/* ------------------------------------------------------------------ */
/*  Progress / unlock state                                            */
/* ------------------------------------------------------------------ */

/** Per-knowledge-check progress for a user. */
export interface CheckProgress {
  n: number;
  bestScore: number;
  attempts: number;
  /** bestScore >= 80 — 80 flat passes. */
  passed: boolean;
}

/** Exam unlock state derived from all checks. */
export interface ExamUnlockState {
  checks: CheckProgress[];
  /** Every check passed at >= 80. */
  allPassed: boolean;
}

/* ------------------------------------------------------------------ */
/*  Exam batch grading                                                 */
/* ------------------------------------------------------------------ */

export interface ExamAnswer {
  questionIndex: number;
  userAnswerIndex: number;
}

export interface ExamSubmitRequest {
  quizName: string;
  /** Client-reported elapsed seconds; server rejects outside [0, 105*60 + 60]. */
  elapsedSeconds: number;
  answers: ExamAnswer[];
}

export interface ExamResultItem {
  questionIndex: number;
  isCorrect: boolean;
  /**
   * Correct answer index — OMITTED for unanswered questions (server-side
   * security fix t_c0c452f5, CWE-200): a partial/empty answer set must never
   * leak the exam key. Only present when the question was actually answered.
   */
  correctAnswerIndex?: number;
}

export interface ExamSubmitResult {
  /** 0-100. */
  score: number;
  correct: number;
  total: number;
  /** score >= 72. */
  passed: boolean;
  /** Per-question results for the review screen (never shipped pre-submit). */
  results: ExamResultItem[];
}

/* ------------------------------------------------------------------ */
/*  Tier progress endpoint (GET /api/progress/quiz/tiers)              */
/* ------------------------------------------------------------------ */

export interface TierProgress {
  lessons: { completed: number; total: number };
  checks: CheckProgress[];
  exam: { bestScore: number; attempts: number; passed: boolean };
  /** All checks passed >= 80 → exam unlocked. */
  unlocked: boolean;
}

/* ------------------------------------------------------------------ */
/*  Certificate                                                        */
/* ------------------------------------------------------------------ */

export interface CertificateEligibility {
  eligible: boolean;
  lessonsCompleted: number;
  lessonsTotal: number;
  examBest: number;
  examPassed: boolean;
  checksPassed: number;
  checksTotal: number;
}

/* ------------------------------------------------------------------ */
/*  Readiness rollup (series page)                                     */
/* ------------------------------------------------------------------ */

export interface ReadinessRollup {
  lessonsCompleted: number;
  lessonsTotal: number;
  checksPassed: number;
  checksTotal: number;
  examBest: number;
  /** Weighted: lessons 40% / checks 30% / exam best 30%. */
  readinessPct: number;
}
