/**
 * GENERATED by scripts/build-audio.js — do not hand-edit.
 * Regenerate with: node scripts/build-audio.js --recent N --voice <v>
 * Contract types: src/lib/audio/contracts.ts.
 */
import type { ArticleAudio } from "@/lib/audio/contracts";

export const articleAudio: ArticleAudio[] = [
  { slug: "agent-eval-infrastructure-2026", voice: "af_heart", storagePath: "blog/agent-eval-infrastructure-2026/af_heart.mp3" },
  { slug: "backup-restore-validation-2026", voice: "af_heart", storagePath: "blog/backup-restore-validation-2026/af_heart.mp3" },
  { slug: "prompt-caching-ai-infrastructure-2026", voice: "af_heart", storagePath: "blog/prompt-caching-ai-infrastructure-2026/af_heart.mp3" },
  { slug: "realtime-subscription-lifecycle-supabase-2026", voice: "af_heart", storagePath: "blog/realtime-subscription-lifecycle-supabase-2026/af_heart.mp3" },
  { slug: "salesforce-release-discipline-2026", voice: "af_heart", storagePath: "blog/salesforce-release-discipline-2026/af_heart.mp3" },
  { slug: "salesforce-summer-26-three-things", voice: "af_heart", storagePath: "blog/salesforce-summer-26-three-things/af_heart.mp3" },
  { slug: "sse-vs-websockets-2026", voice: "af_heart", storagePath: "blog/sse-vs-websockets-2026/af_heart.mp3" },
];
