/**
 * GENERATED by scripts/build-audio.js — do not hand-edit.
 * Regenerate with: node scripts/build-audio.js --recent N --voice <v>
 * Contract types: src/lib/audio/contracts.ts.
 */
import type { ArticleAudio } from "@/lib/audio/contracts";

export const articleAudio: ArticleAudio[] = [
  { slug: "agent-eval-infrastructure-2026", voice: "af_heart", storagePath: "blog/agent-eval-infrastructure-2026/af_heart.mp3" },
  { slug: "state-of-the-stack-september-2026", voice: "af_heart", storagePath: "blog/state-of-the-stack-september-2026/af_heart.mp3" },
];
