/**
 * GENERATED by scripts/build-audio.js --learn - do not hand-edit.
 * Regenerate with: node scripts/build-audio.js --learn --voice <v>
 * Contract types: src/lib/audio/contracts.ts.
 */
import type { LessonAudio } from "@/lib/audio/contracts";

export const lessonAudio: LessonAudio[] = [
  { series: "agentic-ai", slug: "agent-frameworks-overview-langchain-langgraph-crewai-openai-claude", voice: "af_heart", storagePath: "learn/agentic-ai/agent-frameworks-overview-langchain-langgraph-crewai-openai-claude/af_heart.mp3", timingsStoragePath: "learn/agentic-ai/agent-frameworks-overview-langchain-langgraph-crewai-openai-claude/af_heart.timing.json" },
  { series: "agentic-ai", slug: "agent-loop-by-hand-no-framework", voice: "af_heart", storagePath: "learn/agentic-ai/agent-loop-by-hand-no-framework/af_heart.mp3", timingsStoragePath: "learn/agentic-ai/agent-loop-by-hand-no-framework/af_heart.timing.json" },
];
