/**
 * GENERATED by scripts/build-audio.js --learn — do not hand-edit.
 * Regenerate with: node scripts/build-audio.js --learn --voice <v>
 * Contract types: src/lib/audio/contracts.ts.
 */
import type { LessonAudio } from "@/lib/audio/contracts";

export const lessonAudio: LessonAudio[] = [
];
